"""GitLab issue export - generates issue templates and bulk import files."""

from __future__ import annotations

import csv
import json
from datetime import datetime
from pathlib import Path
from typing import Optional

from .models import Action, ActionStatus, Priority


# Priority to GitLab label mapping
PRIORITY_LABELS = {
    Priority.CRITICAL.value: "priority::critical",
    Priority.HIGH.value: "priority::high",
    Priority.MEDIUM.value: "priority::medium",
    Priority.LOW.value: "priority::low",
    Priority.INFORMATIONAL.value: "priority::informational",
}

STATUS_LABELS = {
    ActionStatus.TODO.value: "status::todo",
    ActionStatus.IN_PROGRESS.value: "status::in-progress",
    ActionStatus.IN_PLANNING.value: "status::planning",
    ActionStatus.RISK_ACCEPTED.value: "status::risk-accepted",
    ActionStatus.COMPLETED.value: "status::completed",
    ActionStatus.NOT_APPLICABLE.value: "status::not-applicable",
    ActionStatus.THIRD_PARTY.value: "status::third-party",
}


def _build_issue_body(action: Action, tenant_name: str = "") -> str:
    """Build a markdown body for a GitLab issue."""
    lines = []

    lines.append(f"## {action.title}")
    lines.append("")

    if tenant_name:
        lines.append(f"**Tenant:** {tenant_name}")
    lines.append(f"**Source:** {action.source_tool}")
    lines.append(f"**Source ID:** {action.source_id}")
    lines.append(f"**Workload:** {action.workload}")
    lines.append(f"**Priority:** {action.priority}")
    lines.append(f"**Risk Level:** {action.risk_level}")
    lines.append(f"**User Impact:** {action.user_impact}")
    lines.append(f"**Implementation Effort:** {action.implementation_effort}")

    if action.required_licence:
        lines.append(f"**Required Licence:** {action.required_licence}")
    if action.essential_eight_control:
        lines.append(f"**Essential Eight:** {action.essential_eight_control} ({action.essential_eight_maturity or 'N/A'})")
    if action.score is not None:
        lines.append(f"**Score:** {action.score}/{action.max_score} ({action.score_percentage}%)")
    lines.append("")

    if action.description:
        lines.append("### Description")
        lines.append(action.description)
        lines.append("")

    if action.current_value:
        lines.append("### Current Configuration")
        lines.append(f"```\n{action.current_value}\n```")
        lines.append("")

    if action.recommended_value:
        lines.append("### Recommended Configuration")
        lines.append(f"```\n{action.recommended_value}\n```")
        lines.append("")

    if action.remediation_steps:
        lines.append("### Remediation Steps")
        lines.append(action.remediation_steps)
        lines.append("")

    if action.reference_url:
        lines.append(f"### Reference")
        lines.append(f"[Documentation]({action.reference_url})")
        lines.append("")

    if action.planned_date:
        lines.append(f"**Planned Date:** {action.planned_date}")
    if action.responsible:
        lines.append(f"**Responsible:** {action.responsible}")

    lines.append("")
    lines.append("---")
    lines.append(f"*Generated by M365 Security Posture Tool on {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}*")

    return "\n".join(lines)


def _build_labels(action: Action, extra_labels: list[str] = None) -> str:
    """Build comma-separated label string for GitLab."""
    labels = ["m365-security"]
    labels.append(PRIORITY_LABELS.get(action.priority, "priority::medium"))
    labels.append(STATUS_LABELS.get(action.status, "status::todo"))

    if action.workload:
        labels.append(f"workload::{action.workload.lower().replace(' ', '-')}")
    if action.source_tool:
        labels.append(f"source::{action.source_tool.lower().replace(' ', '-').replace('(', '').replace(')', '')}")
    if action.essential_eight_control:
        labels.append("essential-eight")

    if extra_labels:
        labels.extend(extra_labels)

    return ",".join(labels)


def export_to_gitlab_csv(
    actions: list[Action],
    output_path: str,
    tenant_name: str = "",
    filter_status: list[str] = None,
) -> str:
    """Export actions to GitLab-compatible CSV for bulk issue import.

    GitLab CSV import format:
    title, description, due_date, milestone, labels, assignee
    """
    if filter_status:
        actions = [a for a in actions if a.status in filter_status]

    path = Path(output_path)
    with open(path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["title", "description", "due_date", "labels", "assignee"])

        for action in actions:
            title = f"[{action.workload}] {action.title}"
            if len(title) > 255:
                title = title[:252] + "..."

            body = _build_issue_body(action, tenant_name)
            due_date = action.planned_date or ""
            labels = _build_labels(action)
            assignee = action.responsible or ""

            writer.writerow([title, body, due_date, labels, assignee])

    return str(path)


def export_to_gitlab_json(
    actions: list[Action],
    output_path: str,
    tenant_name: str = "",
    project_id: Optional[int] = None,
    filter_status: list[str] = None,
) -> str:
    """Export actions as JSON array of GitLab issue objects (for API import)."""
    if filter_status:
        actions = [a for a in actions if a.status in filter_status]

    issues = []
    for action in actions:
        issue = {
            "title": f"[{action.workload}] {action.title}"[:255],
            "description": _build_issue_body(action, tenant_name),
            "labels": _build_labels(action),
            "due_date": action.planned_date or None,
            "assignee": action.responsible or None,
            "confidential": False,
        }
        if project_id:
            issue["project_id"] = project_id
        issues.append(issue)

    path = Path(output_path)
    with open(path, "w") as f:
        json.dump(issues, f, indent=2)

    return str(path)


def generate_gitlab_script(
    actions: list[Action],
    output_path: str,
    tenant_name: str = "",
    project_path: str = "GROUP/PROJECT",
    filter_status: list[str] = None,
) -> str:
    """Generate a shell script that uses gitlab CLI or API to create issues."""
    if filter_status:
        actions = [a for a in actions if a.status in filter_status]

    lines = ["#!/bin/bash", "# GitLab issue creation script",
             f"# Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}",
             f"# Tenant: {tenant_name}", "",
             f'PROJECT="{project_path}"', ""]

    for action in actions:
        title = f"[{action.workload}] {action.title}"[:255].replace('"', '\\"')
        labels = _build_labels(action)
        due = f'--due-date "{action.planned_date}"' if action.planned_date else ""
        assignee = f'--assignee "{action.responsible}"' if action.responsible else ""

        lines.append(f'echo "Creating issue: {title[:60]}..."')
        lines.append(
            f'glab issue create --project "$PROJECT" '
            f'--title "{title}" '
            f'--label "{labels}" '
            f'{due} {assignee} '
            f'--description "Source: {action.source_tool} | ID: {action.source_id} | '
            f'Priority: {action.priority} | Risk: {action.risk_level}"'
        )
        lines.append("")

    lines.append('echo "Done! Created issues for all actions."')

    path = Path(output_path)
    with open(path, "w") as f:
        f.write("\n".join(lines))

    return str(path)
